# Generated by Django 5.1.7 on 2025-06-01 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'document_category_master',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_name', models.CharField(max_length=255)),
                ('upload_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.documentcategorymaster')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('conversion_meta_data', models.JSONField()),
                ('converted_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.documents')),
            ],
            options={
                'db_table': 'document_conversion',
            },
        ),
    ]
