# Generated by Django 5.1.7 on 2025-06-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_auto_20250601201133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
